services:
  - type: web
    name: barberini-api
    runtime: docker
    plan: free
    region: oregon
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: postgres
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_SEED_DONO_EMAIL
        value: dono@barberini.com
      - key: APP_SEED_DONO_SENHA
        value: dono123
      - key: GOOGLE_CLIENT_ID
        value: 868389533637-d3l4a0mrnnbf7i1h34cd0mts996sb6pc.apps.googleusercontent.com
